### ISSUE TITLE
method for downloading resource content - does it exist?

### ISSUE THREAD

**Issue by mattkime** [alicoding/node-transifex#11]
looking through the code and the docs i've failed to find a method for downloading resource content. am i missing it or does it need to be added?

it seems like it would be simple to add.

**Comment by alicoding** [comment]
@mattkime Is [sourceLanguageMethods
](https://github.com/alicoding/node-transifex#sourcelanguagemethods) not what you're looking for?

**Comment by mattkime** [comment]
thats it! thanks @alicoding
