### ISSUE TITLE
support uploading of translation content 

### ISSUE THREAD

**Issue by mattkime** [alicoding/node-transifex#15]
support uploading of translation content - http://docs.transifex.com/api/translations/#put

**Comment by mattkime** [comment]
@alicoding I can close this once the latest commit it pushed to npm. 

here's an example of a `.travis.yml` that does this automatically - https://github.com/meetup/meetup-web-platform/blob/master/.travis.yml

**Comment by alicoding** [comment]
@mattkime I've published this to npm and going to implement that auto publish to npm soon 👍
