### ISSUE TITLE
why "preferGlobal": true ?

### ISSUE THREAD

**Issue by mattkime** [alicoding/node-transifex#9]
why does `package.json` specifies `"preferGlobal": true`? 

This produces a `npm WARN` message. Sometimes these messages are important. Ideally, they'd always be important. Therefore its best to remove unnecessary warnings.

I can make a PR in short order, just wanted to discuss first.

Thanks!

**Comment by alicoding** [comment]
Thanks for opening up an issue! The preferred global actually can be removed since the CLI in this package is barely used by many people (mostly internally at mozilla). Will gladly accept your PR
